In [1]:
import numpy as np

## 1. Stwórz 1D tablicę NumPy zawierającą liczby od 10 do 50 co 5.

In [2]:
np.arange(10,51,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

## 2. Zmień kształt tablicy `[1, 2, 3, 4, 5, 6]` na tablicę 2x3.

In [4]:
np.array([1,2,3,4,5,6]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

## 3. Stwórz macierz jednostkową o wymiarach 5x5.

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 4. Oblicz sumę elementów w każdej kolumnie poniższej macierzy:
```python
a = np.array([[1, 2], [3, 4], [5, 6]])
```

In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a.sum(axis = 1)

array([ 3,  7, 11])

## 5. Zrób *broadcasting* i dodaj do każdej kolumny tej macierzy wartość `[10, 100]`.
```python
a = np.array([[1, 2], [3, 4], [5, 6]])
```

In [15]:
a = np.array([[1,2],[3,4],[5,6]])
a + np.array([10,100])

array([[ 11, 102],
       [ 13, 104],
       [ 15, 106]])

## 6. Oblicz iloczyn macierzy `A` i `B`.
```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
```

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A * B)
print(A @ B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


## 7. Wygeneruj losową tablicę o rozmiarze 4x4 z wartościami z przedziału [0, 1).

In [31]:
np.random.randint(2, size = 16).reshape(4,4)

array([[0, 1, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0]], dtype=int32)

## 8. Znajdź maksymalną i minimalną wartość w poniższej tablicy.
```python
arr = np.array([3, 1, 4, 1, 5, 9])
```

In [33]:
arr = np.array([3,1,4,1,5,9])
print(np.max(arr))
print(np.min(arr))

9
1



## 9. Sprawdź, które elementy w poniższej tablicy są większe niż 3.
```python
arr = np.array([2, 4, 3, 5, 1])
```

In [37]:
arr = np.array([2,4,3,5,1])
arr > 3

array([False,  True, False,  True, False])

## 10. Zmień typ danych tablicy z `int` na `float`.
```python
arr = np.array([1, 2, 3])
```

In [47]:
arr = np.array([1,2,3])
arr.astype(float)

array([1., 2., 3.])

## 11. Wyciągnij podtablicę z wiersza 2 i kolumn 1–2 z poniższej macierzy.
```python
a = np.arange(20).reshape(4, 5)
```

In [51]:
a = np.arange(20).reshape(4,5)
a[2,1:3]

array([11, 12])

## 12. Oblicz średnią, medianę i wariancję poniższej tablicy.
```python
arr = np.array([1, 2, 3, 4, 5])
```

In [54]:
arr = np.array([1,2,3,4,5])
print(arr.mean())
print(np.median(arr))
print(arr.var())

3.0
3.0
2.0


## 13. Wygeneruj tablicę 10 liczb całkowitych z przedziału [0, 100), ale tylko parzystych.

In [55]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

## 14. Ustaw wszystkie elementy większe niż 50 na 50.
```python
arr = np.array([34, 67, 89, 23, 50])
```

In [58]:
arr = np.array([34,67,89,23,50])
arr[arr > 50] = 50
arr

array([34, 50, 50, 23, 50])

## 15. Wylosuj ziarno `42` i wygeneruj 5 losowych liczb z rozkładu normalnego.

In [61]:
np.random.seed(42)
np.random.randn(5)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])

## 16. Znormalizuj dane tak, aby miały średnią 0 i odchylenie standardowe 1.
```python
data = np.array([10, 12, 14, 16, 18])
```

In [65]:
data = np.array([10,12,14,16,18])
(data - data.mean())/data.std()

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

## 17. Użyj `np.dot` i `@` do mnożenia dwóch wektorów i pokaż, że wynik jest ten sam.
```python
a = np.array([1, 2])
b = np.array([3, 4])
```

In [66]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.dot(a,b))
print(a @ b)

11
11


## 18. Wytłumacz, czym różni się `np.copy()` od przypisania `b = a`.
*(Wpisz odpowiedź jako komentarz)*

## 19. Oblicz iloczyn skalarny dwóch wektorów.
```python
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
```

## 20. Wytłumacz na czym polega `broadcasting` i podaj przykład jego działania.
*(Wpisz odpowiedź jako komentarz + kod)*