In [1]:
import numpy as np

In [2]:
a = np.zeros((2,3,4,5))

In [3]:
a.ndim

4

In [4]:
a = np.full((5,5), -1)
print(a)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [5]:
b = np.empty((5,5))
print(b)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.20161797e-306
  2.22523004e-307]
 [1.78020440e-306 1.42417221e-306 1.33511969e-306 1.33511018e-306
  3.44894088e-307]
 [7.56577398e-307 1.33511562e-306 9.34582628e-307 1.11261162e-306
  8.34441742e-308]
 [1.95821439e-306 8.01097889e-307 1.78020169e-306 7.56601165e-307
  1.02359984e-306]
 [1.33510679e-306 2.22522597e-306 8.01097889e-307 3.27028770e-317
  0.00000000e+000]]


In [6]:
b.fill(99)
print(b)

[[99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99.]]


In [7]:
c = b - a
print(c)

[[100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100.]]


In [8]:
a = np.arange(0,24)
a = a.reshape(2,3,4)
print(f'a array:\n{a}\n')
print(f'shape:\n{a.shape}\n')
print(f'ndim:\n{a.ndim}\n')
print(f'dtype:\n{a.dtype}\n')
print(f'size:\n{a.size}\n')

a array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

shape:
(2, 3, 4)

ndim:
3

dtype:
int64

size:
24



In [9]:
a = a.astype('float32')
print(a)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


In [10]:
a = a[:] * 0.2

In [11]:
print('przed round:\n')
np.set_printoptions(precision=10)  # ← TO DODAJ TUTAJ
print(a)

a = a.round(3)
print('\npo round:\n')
print(a)


przed round:

[[[0.        0.2       0.4       0.6      ]
  [0.8       1.        1.2       1.4      ]
  [1.6       1.8000001 2.        2.2      ]]

 [[2.4       2.6000001 2.8       3.       ]
  [3.2       3.4       3.6000001 3.8      ]
  [4.        4.2000003 4.4       4.6      ]]]

po round:

[[[0.  0.2 0.4 0.6]
  [0.8 1.  1.2 1.4]
  [1.6 1.8 2.  2.2]]

 [[2.4 2.6 2.8 3. ]
  [3.2 3.4 3.6 3.8]
  [4.  4.2 4.4 4.6]]]


In [12]:
a = np.arange(0, 2, 0.3333)
b = np.linspace(0, 2, len(a))
print(a)
print('\n')
print(b)
print(np.allclose(a, b, rtol=1e-03, atol=1e-05))  # Porównuje z tolerancją
print(np.array_equal(a, b))  # Porównuje ściśle


[0.     0.3333 0.6666 0.9999 1.3332 1.6665 1.9998]


[0.           0.3333333333 0.6666666667 1.           1.3333333333
 1.6666666667 2.          ]
True
False


In [13]:
a = np.arange(0,2,0.4)
b = np.linspace(0,1.6,5)
print(a)
print(b)
print(np.allclose(a,b))

[0.  0.4 0.8 1.2 1.6]
[0.  0.4 0.8 1.2 1.6]
True


In [14]:
a = np.arange(2.5, 6.1, 0.3)
b = np.linspace(2.5, a[-1], len(a))
print(a)
print(b)
print(np.allclose(a,b))

print('\n')

c = np.linspace(-2,3,11)
print(c)
print(np.diff(c))

[2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9 5.2 5.5 5.8]
[2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9 5.2 5.5 5.8]
True


[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


In [15]:
def my_function(z,y,x):
    return 100 * z + 10 * y + x
np.fromfunction(my_function, (2, 3, 4))

array([[[  0.,   1.,   2.,   3.],
        [ 10.,  11.,  12.,  13.],
        [ 20.,  21.,  22.,  23.]],

       [[100., 101., 102., 103.],
        [110., 111., 112., 113.],
        [120., 121., 122., 123.]]])

In [16]:
d = np.arange(1,65, dtype = 'int16')
print(d.dtype == np.int8)
print(d.dtype == 'int8')
print(d.itemsize)
print(d.size)
print(d.size * d.itemsize)

False
False
2
64
128


In [17]:
g = np.arange(1,25)
print(g)
g.shape = (2,12)
print(g)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [18]:
h = np.arange(24)
h2 = h.reshape(4,6)
print(h,'\n\n\n',h2)

h2[1,0] = 621
print('\n\n',h2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 


 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


 [[  0   1   2   3   4   5]
 [621   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]


In [19]:
h3 = h2.ravel()
print(h3)
print('\n')
h3[-1] = 99
print(h3)
print('\n')
print(h2)

[  0   1   2   3   4   5 621   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]


[  0   1   2   3   4   5 621   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  99]


[[  0   1   2   3   4   5]
 [621   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  99]]


In [20]:
i = np.arange(5)
i = i + [[[10,20,30,40,50]]]
print(i)

[[[10 21 32 43 54]]]


In [21]:
i = i.ravel()
print(i)

[10 21 32 43 54]


In [22]:
i.shape == (2,3)

False

In [23]:
k1 = np.arange(5, dtype = np.int8)
print(k1.dtype, k1)

int8 [0 1 2 3 4]


In [24]:
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

uint8 [0 1 2 3 4]


In [25]:
k2 = k1 + np.array([5,6,7,8,9], dtype = np.int8)
print(k2.dtype, k2)

int16 [ 5  7  9 11 13]


In [26]:
a = np.arange(5)
for func in (a.min, a.max):
    print(func.__name__, "=", func())

min = 0
max = 4


In [27]:
c = np.arange(24).reshape(2,3,4)
print('oryginal:\n',c,'\n')
print('sum():"\n',c.sum(), '\n')
print('sum(axis = 0):\n',c.sum(axis = 0), '\n')
print('sum(axis = 1):\n',c.sum(axis = 1), '\n')
print('sum(axis = 2):\n',c.sum(axis = 2), '\n')

oryginal:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

sum():"
 276 

sum(axis = 0):
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 

sum(axis = 1):
 [[12 15 18 21]
 [48 51 54 57]] 

sum(axis = 2):
 [[ 6 22 38]
 [54 70 86]] 



In [28]:
np.square(c)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]])

In [29]:
print(c,'\n\n')
print(c[:,:,(-1,1)])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 


[[[ 3  1]
  [ 7  5]
  [11  9]]

 [[15 13]
  [19 17]
  [23 21]]]


In [30]:
t = np.arange(24).reshape(4,2,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [31]:
t1 = t.transpose((1,2,0))
t1

array([[[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20]],

       [[ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]]])

In [32]:
m1 = np.arange(10).reshape(2,5)
print(m1)
np.shape(m1.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]


(5, 2)

In [33]:
n1 = np.arange(10).reshape(2,5)
n1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
n2 = np.arange(15).reshape(5,3)
n2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [35]:
n1.dot(n2)

array([[ 90, 100, 110],
       [240, 275, 310]])

In [36]:
import numpy.linalg as linalg

m3 = np.array([[1,2,3],[5,7,11],[21,29,31]])
m3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [37]:
print(m3,'\n\n')
m4 = linalg.inv(m3)
print(m4,'\n\n')
m5 = m3 @ m4
print(m5,'\n\n')

[[ 1  2  3]
 [ 5  7 11]
 [21 29 31]] 


[[-2.3181818182  0.5681818182  0.0227272727]
 [ 1.7272727273 -0.7272727273  0.0909090909]
 [-0.0454545455  0.2954545455 -0.0681818182]] 


[[ 1.0000000000e+00 -1.6653345369e-16  0.0000000000e+00]
 [ 6.3143934526e-16  1.0000000000e+00 -1.3877787808e-16]
 [ 5.2111093218e-15 -2.3869795029e-15  1.0000000000e+00]] 




In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])